--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <eks-cluster-name> # e.g. wazuh-eks-cluster
  region: <aws-region> # e.g. us-east-1

nodeGroups:
  - name: wazuh-ng-private
    instanceType: m5a.large
    ssh: # use existing EC2 key but don't allow SSH access to nodegroup (security group is not created to allow SSH access).
      allow: false
      publicKeyName: <keypair-name>
    desiredCapacity: 3
    privateNetworking: true #turn to false for public networks.
